export const weapon_data = {
  lance: {
    icon: "🔱",
    dmg_type: "melee",
    fightBonus: 1.3,
    uses: [4, 9],
    class: Lance,
    value: 28,
    odds: 25,
  },
  gun: {
    icon: "🔫",
    dmg_type: "ranged",
    rangeBonus: 20,
    fightBonus: 1.3,
    uses: 4,
    value: 35,
    odds: 20,
  },
  bow: {
    icon: "🏹",
    dmg_type: "ranged",
    rangeBonus: 30,
    fightBonus: 1.1,
    uses: 8,
    value: 15,
    odds: 20,
  },
  knife: {
    icon: "🔪",
    dmg_type: "melee",
    fightBonus: 1.1,
    uses: [5, 10],
    value: 10,
    odds: 30,
  },
  wand: {
    icon: "🪄",
    dmg_type: "magic",
    fightBonus: 1.1,
    rangeBonus: 24,
    uses: [3, 6],
    value: 20,
    odds: 18,
  },
  katana: {
    icon: "./icons/katana.png",
    icon_type: "img",
    dmg_type: "melee",
    uses: [4, 9],
    class: Katana,
    value: 25,
    odds: 25,
  },
  shotgun: {
    icon: "./icons/shotgun.png",
    icon_type: "img",
    rangeBonus: 25,
    dmg_type: "ranged",
    uses: [3, 6],
    class: Shotgun,
    value: 30,
    odds: 25,
  },
};

//offhand
export const offhand_data = {
  bomb: {
    icon: "💣",
    uses: 1,
    class: Bomb,
    value: 30,
  },
  trap: {
    icon: "🕳",
    uses: 1,
    class: Trap,
    value: 25,
  },
  shield: {
    // "icon":"🛡️",
    icon: "./icons/shield.png",
    icon_type: "img",
    uses: [1, 3],
    dmgReductionB: 0.5,
    useStates: ["defend"],
    value: 15,
  },
  recoil: {
    icon: "./icons/recoil.png",
    icon_type: "img",
    dmgReductionB: 0.75,
    uses: 10,
    class: Recoil,
    value: 5,
  },
  vape: {
    icon: "./icons/vape.png",
    icon_type: "img",
    peaceBonus: 40,
    visibilityB: -20,
    uses: 1,
    class: Vape,
    value: 0,
  },
  campfire: {
    icon: "./icons/campfire.png",
    icon_type: "img",
    uses: 1,
    class: Campfire,
    value: 25,
  },
  mirror: {
    icon: "./icons/mirror.png",
    icon_type: "img",
    uses: 1,
    class: Mirror,
    value: 40,
  },
  doll: {
    icon: "./icons/doll.png",
    icon_type: "img",
    uses: 1,
    class: Doll,
    value: 100,
  },
  dinh: {
    icon: "./icons/dinh.png",
    icon_type: "img",
    uses: 70,
    class: Dinh,
    value: 60,
  },
};

//food
export const food_data = {
  apple: {
    icon: "🍎",
    uses: [1, 5],
    heal: 8,
    value: 8,
  },
  pie: {
    icon: "🥧",
    uses: 1,
    heal: 20,
    value: 20,
  },
  banana: {
    icon: "🍌",
    uses: [2, 4],
    heal: 8,
    energy_heal: 10,
    value: 10,
  },
  health_potion: {
    icon: "?",
    uses: [2, 4],
    heal: 8,
    value: 8,
  },
  str_potion: {
    icon: "./icons/str_pot.png",
    icon_type: "img",
    uses: 1,
    class: StrPotion,
    value: 20,
  },
  ebiroll: {
    icon: "🦐",
    uses: 1,
    heal: 30,
    class: Ebiroll,
    value: 29,
  },
  purple: {
    icon: "./icons/purpleSweet.png",
    icon_type: "img",
    uses: [5, 10],
    heal: 1,
    energy_heal: 5,
    class: PurpleSweet,
    value: 4,
  },
  onigiri: {
    icon: "🍙",
    uses: [3, 7],
    heal: 5,
    value: 5,
  },
  soup: {
    icon: "🥣",
    uses: 1,
    heal: 12,
    energy_heal: 2,
    value: 14,
  },
  pizza: {
    icon: "🍕",
    uses: 8,
    heal: 5,
    value: 5,
  },
  orange: {
    icon: "🍊",
    uses: [3, 10],
    heal: 3,
    value: 3,
  },
  spaghetti: {
    icon: "🍝",
    uses: [2, 3],
    heal: 5,
    value: 5,
  },
  "beef stroganoff": {
    icon: "🍲",
    uses: [2, 4],
    heal: 6,
    value: 5,
  },
  chicken: {
    icon: "🍗",
    uses: 2,
    heal: 5,
    value: 5,
  },
};
